import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import { VisitTracker } from "@/components/layout/VisitTracker";
import "./globals.css";
import "leaflet/dist/leaflet.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { SessionProvider } from "next-auth/react"
import { db } from "@/db"
import { settings } from "@/db/schema"
import { eq } from "drizzle-orm"

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let settingsData: Record<string, string> = {}
  try {
    const res = await db.select().from(settings)
    res.forEach(s => {
      settingsData[s.key] = s.value || ''
    })
  } catch (e) {
    // Table might not exist yet or other DB error
  }

  const gscCode = settingsData.google_search_console
  const siteTitle = settingsData.site_title || "QuedaMoto"
  const siteFavicon = settingsData.site_favicon

  return (
    <html
      lang="es"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        <title>{siteTitle}</title>
        {siteFavicon && <link rel="icon" href={siteFavicon} />}
        {gscCode && (
          gscCode.startsWith('<') 
            ? <script dangerouslySetInnerHTML={{ __html: gscCode }} />
            : <meta name="google-site-verification" content={gscCode} />
        )}
      </head>
      <body className="min-h-full flex flex-col" suppressHydrationWarning>
        <SessionProvider>
          <VisitTracker />
          {children}
        </SessionProvider>
        <Toaster position="bottom-right" />
      </body>
    </html>
  );
}
