import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import { VisitTracker } from "@/components/layout/VisitTracker";
import "./globals.css";
import "leaflet/dist/leaflet.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { SessionProvider } from "next-auth/react"
import { db } from "@/db"
import { settings } from "@/db/schema"
import { eq } from "drizzle-orm"

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let gscCode = null
  try {
    const res = await db.select().from(settings).where(eq(settings.key, 'google_search_console')).limit(1)
    gscCode = res[0]?.value
  } catch (e) {
    // Table might not exist yet or other DB error
  }

  return (
    <html
      lang="es"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        {gscCode && (
          gscCode.startsWith('<') 
            ? <script dangerouslySetInnerHTML={{ __html: gscCode }} />
            : <meta name="google-site-verification" content={gscCode} />
        )}
      </head>
      <body className="min-h-full flex flex-col" suppressHydrationWarning>
        <SessionProvider>
          <VisitTracker />
          {children}
        </SessionProvider>
        <Toaster position="bottom-right" />
      </body>
    </html>
  );
}
